Test\EventBundle\Entity\Guests:
  type: entity
  table: guests
  id:
    id:
      type: integer 
      generator: { strategy: AUTO }
  fields:
   name:
    type: string
    length: 225
   email:
    type: string
    length: 225
   isAttending:
    type: boolean
    nullable: true