parameters:
#    test_event.example.class: Test\EventBundle\Example

services:
#    test_event.example:
#        class: %test_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
