<?php

namespace Test\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuestssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestssRepository extends EntityRepository
{
}
